### ISSUE TITLE
use OpenAPI to specify API?

### ISSUE THREAD

**Issue by teo8192** [Frixxie/elo_leaderboard_system#5]
A JSON/YAML file specifying how the API works, use this to integrate with some GitHub Actions for testing the API

**Comment by Frixxie** [comment]
Good idea, we should do that!

**Comment by Frixxie** [comment]
This could be a tool to autogenerate the API documentation: https://github.com/juhaku/utoipa

**Comment by teo8192** [comment]
working on finding a tool to automatically test the API using the OpenAPI spec.
